name: release


on: create


jobs:

  release:

    # Only run upon creation of a version tag.
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}

    runs-on: ubuntu-latest

    # Grant permissions to GITHUB_TOKEN. (`actions/checkout` embeds it into `remote.origin.url`.)
    permissions:
      contents: write
      id-token: write

    env:
      MODULE: "colab_assist"
      PKG: "colab-assist"

    steps:

    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # https://docs.astral.sh/uv/guides/integration/github/#caching
    - uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true

    - name: Build package
      run: uv build

    - name: Publish to TestPyPI
      env:
        PUBLISH_URL: "https://test.pypi.org/legacy/"
      run:
        uv publish --publish-url "$PUBLISH_URL"

    - name: Test installation from TestPyPI
      env:
        INDEX_URL: "https://test.pypi.org/simple/"
      run: uv run --with "$PKG" --default-index "$INDEX_URL" --no-project -- python -c "import $MODULE"

    - name: Publish to PyPI
      run: uv publish

    - name: Test installation from PyPI
      run: uv run --with "$PKG" --refresh --no-project -- python -c "import $MODULE"

    - name: Create GitHub release
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TAG: ${{ github.ref_name }}
      run: |
        release_note=$(uvx --from git-cliff git cliff -l)
        gh release create "$TAG" -t "$TAG" -n "$release_note" ./dist/*.tar.gz ./dist/*.whl
